# Taken from http://ark.gamepedia.com/Color_IDs

$DinoColors = @(
    "ZERO",   # Because arrays are zero-based, but the list is 1-based
    "Red",
    "Blue",
    "Green",
    "Yellow",
    "Cyan",
    "Magenta",
    "L. Green",
    "L. Grey",
    "L. Brown",
    "L. Orange",
    "L. Yellow",
    "L. Red",
    "D. Grey",
    "Black",
    "Brown",
    "D. Green",
    "D. Red",
    "White",
    "L. Red",
    "D. Red",
    "L. Orange",
    "D. Orange",
    "L. Yello",
    "D. Yellow",
    "L. Green",
    "M. Green",
    "D. Green",
    "L. Blue",
    "D. Blue",
    "L. Purple",
    "D. Purple",
    "L. Brown",
    "M. Brown",
    "D. Brown",
    "D.er Grey",
    "Albino",
    "BigFoot0",
    "BigFoot4",
    "BigFoot5",
    "Wolf Fur",
    "D. Wolf Fur",
    "DragonBase0",
    "DragonBase1",
    "DragonFire",
    "DragonGreen0",
    "DragonGreen1",
    "DragonGreen2",
    "DragonGreen3",
    "WyvernPurple0",
    "WyvernPurple1",
    "WyvernBlue0",
    "WyvernBlue1",
    "Dino M. Blue",
    "Dino Deep Blue",
    "NearWhite",
    "NearBlack"
)